### ISSUE TITLE
571 - houndmaster wastes taunt

### ISSUE THREAD

**Issue by myParakeet** [sliverfishes/silverfish#25]
Turn 7: http://pastebin.com/EqURCw5X

Houndmaster is used on a minion that already had taunt when alternatives exist. No obvious advantage to doing so.

**Comment by myParakeet** [comment]
I am not sure why double taunting the 3/3 spider to make a 5/5 has such a good playfield value compared to targeting the 1/1 spider or the kings elekk. A very high penalty on "wasting taunt" is needed to overcome the board value.

**Comment by sliverfishes** [comment]
buffing it again prevents the enemy 3/3 from trading with it, not a bug
